### ISSUE TITLE
Insurance Template - Save

### ISSUE THREAD

**Issue by Ruben-Yash** [rakshitdoshi2511/YashInternalTracker#6]
Save in the insurance template doesn't do anything.
Doesn't seems to be working.
![image](https://github.com/user-attachments/assets/af511d5b-ea34-44d8-8baa-4a1b4a8e1d5f)

**Comment by Ruben-Yash** [comment]
Only the coverage section is mandatory.
To add the * for mandatory fields and an error message in case something is missing when clicking save.

**Comment by rakshitdoshi2511** [comment]
> Only the coverage section is mandatory. To add the * for mandatory fields and an error message in case something is missing when clicking save.

This is done

**Comment by Ruben-Yash** [comment]
Save button doesn't work yet, is not saving and not showing any message either
