### ISSUE TITLE
Insurance Template - Edit

### ISSUE THREAD

**Issue by Ruben-Yash** [rakshitdoshi2511/YashInternalTracker#8]
When editing an existing insurance template some fields are empty:
![image](https://github.com/user-attachments/assets/41bc65cc-e745-4515-92d0-04593c7a409e)
![image](https://github.com/user-attachments/assets/61b2b718-e8c6-4b24-bca4-014c0eb613b5)

**Comment by Ruben-Yash** [comment]
Also in display mode, the Criteria should show the description of the code, not only the code.

**Comment by rakshitdoshi2511** [comment]
Both of these are done.
